/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardUsersRouteImport } from './routes/_dashboard/users'
import { Route as DashboardLogsRouteImport } from './routes/_dashboard/logs'
import { Route as DashboardFlagsRouteImport } from './routes/_dashboard/flags'
import { Route as DashboardConfigsRouteImport } from './routes/_dashboard/configs'
import { Route as DashboardOrganizationsIndexRouteImport } from './routes/_dashboard/organizations.index'
import { Route as DashboardOrganizationsOrgIdRouteImport } from './routes/_dashboard/organizations.$orgId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFlagsRoute = DashboardFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfigsRoute = DashboardConfigsRouteImport.update({
  id: '/configs',
  path: '/configs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrganizationsIndexRoute =
  DashboardOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardOrganizationsOrgIdRoute =
  DashboardOrganizationsOrgIdRouteImport.update({
    id: '/organizations/$orgId',
    path: '/organizations/$orgId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/configs': typeof DashboardConfigsRoute
  '/flags': typeof DashboardFlagsRoute
  '/logs': typeof DashboardLogsRoute
  '/users': typeof DashboardUsersRoute
  '/organizations/$orgId': typeof DashboardOrganizationsOrgIdRoute
  '/organizations/': typeof DashboardOrganizationsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/configs': typeof DashboardConfigsRoute
  '/flags': typeof DashboardFlagsRoute
  '/logs': typeof DashboardLogsRoute
  '/users': typeof DashboardUsersRoute
  '/': typeof DashboardIndexRoute
  '/organizations/$orgId': typeof DashboardOrganizationsOrgIdRoute
  '/organizations': typeof DashboardOrganizationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/configs': typeof DashboardConfigsRoute
  '/_dashboard/flags': typeof DashboardFlagsRoute
  '/_dashboard/logs': typeof DashboardLogsRoute
  '/_dashboard/users': typeof DashboardUsersRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/organizations/$orgId': typeof DashboardOrganizationsOrgIdRoute
  '/_dashboard/organizations/': typeof DashboardOrganizationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/configs'
    | '/flags'
    | '/logs'
    | '/users'
    | '/organizations/$orgId'
    | '/organizations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/configs'
    | '/flags'
    | '/logs'
    | '/users'
    | '/'
    | '/organizations/$orgId'
    | '/organizations'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/configs'
    | '/_dashboard/flags'
    | '/_dashboard/logs'
    | '/_dashboard/users'
    | '/_dashboard/'
    | '/_dashboard/organizations/$orgId'
    | '/_dashboard/organizations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/users': {
      id: '/_dashboard/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/logs': {
      id: '/_dashboard/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/flags': {
      id: '/_dashboard/flags'
      path: '/flags'
      fullPath: '/flags'
      preLoaderRoute: typeof DashboardFlagsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/configs': {
      id: '/_dashboard/configs'
      path: '/configs'
      fullPath: '/configs'
      preLoaderRoute: typeof DashboardConfigsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/organizations/': {
      id: '/_dashboard/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof DashboardOrganizationsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/organizations/$orgId': {
      id: '/_dashboard/organizations/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/organizations/$orgId'
      preLoaderRoute: typeof DashboardOrganizationsOrgIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardConfigsRoute: typeof DashboardConfigsRoute
  DashboardFlagsRoute: typeof DashboardFlagsRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardOrganizationsOrgIdRoute: typeof DashboardOrganizationsOrgIdRoute
  DashboardOrganizationsIndexRoute: typeof DashboardOrganizationsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardConfigsRoute: DashboardConfigsRoute,
  DashboardFlagsRoute: DashboardFlagsRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardOrganizationsOrgIdRoute: DashboardOrganizationsOrgIdRoute,
  DashboardOrganizationsIndexRoute: DashboardOrganizationsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
