import type { SeedMeta } from "~shared/seeds";

export const seed: SeedMeta = {
  id: "runtime-configs",
  version: 1,
  description: "Default runtime configuration values",
  data: [
    {
      configKey: "authentication.disableRegister",
      value: "true",
      type: "boolean",
      nullable: false,
      order: 0,
    },
    {
      configKey: "notifications.discord.enable",
      value: "false",
      type: "boolean",
      nullable: false,
      order: 0,
    },
    {
      configKey: "notifications.discord.url",
      value: null,
      type: "string",
      nullable: true,
      order: 1,
      disabled_when: "notifications.discord.enable!=true",
    },
    {
      configKey: "notifications.smtp.enable",
      value: "false",
      type: "boolean",
      nullable: false,
      order: 0,
    },
    {
      configKey: "notifications.smtp.host",
      value: null,
      type: "string",
      nullable: true,
      order: 1,
      disabled_when: "notifications.smtp.enable!=true",
    },
    {
      configKey: "notifications.smtp.port",
      value: null,
      type: "number",
      nullable: true,
      order: 2,
      disabled_when: "notifications.smtp.enable!=true",
    },
    {
      configKey: "notifications.smtp.user",
      value: null,
      type: "string",
      nullable: true,
      order: 3,
      disabled_when: "notifications.smtp.enable!=true",
    },
    {
      configKey: "notifications.smtp.password",
      value: null,
      type: "string",
      nullable: true,
      order: 4,
      disabled_when: "notifications.smtp.enable!=true",
    },
    {
      configKey: "notifications.smtp.fromAddress",
      value: null,
      type: "string",
      nullable: true,
      order: 4,
      disabled_when: "notifications.smtp.enable!=true",
    },
  ],
};
