/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard/profile'
import { Route as DashboardUsersRouteRouteImport } from './routes/_dashboard/users/route'
import { Route as DashboardSettingsRouteRouteImport } from './routes/_dashboard/settings/route'
import { Route as DashboardRolesRouteRouteImport } from './routes/_dashboard/roles/route'
import { Route as DashboardUsersIndexRouteImport } from './routes/_dashboard/users/index'
import { Route as DashboardRolesIndexRouteImport } from './routes/_dashboard/roles/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/_auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as DashboardSettingsSplatRouteImport } from './routes/_dashboard/settings/$'
import { Route as DashboardRolesNameRouteRouteImport } from './routes/_dashboard/roles/$name/route'
import { Route as DashboardUsersUserIdIndexRouteImport } from './routes/_dashboard/users/$userId/index'
import { Route as DashboardRolesNamePermissionsIndexRouteImport } from './routes/_dashboard/roles/$name/permissions/index'
import { Route as DashboardRolesNameMembersIndexRouteImport } from './routes/_dashboard/roles/$name/members/index'
import { Route as DashboardRolesNameDisplayIndexRouteImport } from './routes/_dashboard/roles/$name/_display/index'

const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersRouteRoute = DashboardUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRouteRoute = DashboardSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRolesRouteRoute = DashboardRolesRouteRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardUsersRouteRoute,
} as any)
const DashboardRolesIndexRoute = DashboardRolesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRolesRouteRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardSettingsSplatRoute = DashboardSettingsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DashboardSettingsRouteRoute,
} as any)
const DashboardRolesNameRouteRoute = DashboardRolesNameRouteRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => DashboardRolesRouteRoute,
} as any)
const DashboardUsersUserIdIndexRoute =
  DashboardUsersUserIdIndexRouteImport.update({
    id: '/$userId/',
    path: '/$userId/',
    getParentRoute: () => DashboardUsersRouteRoute,
  } as any)
const DashboardRolesNamePermissionsIndexRoute =
  DashboardRolesNamePermissionsIndexRouteImport.update({
    id: '/permissions/',
    path: '/permissions/',
    getParentRoute: () => DashboardRolesNameRouteRoute,
  } as any)
const DashboardRolesNameMembersIndexRoute =
  DashboardRolesNameMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => DashboardRolesNameRouteRoute,
  } as any)
const DashboardRolesNameDisplayIndexRoute =
  DashboardRolesNameDisplayIndexRouteImport.update({
    id: '/_display/',
    path: '/',
    getParentRoute: () => DashboardRolesNameRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/accept-invitation': typeof AcceptInvitationRoute
  '/roles': typeof DashboardRolesRouteRouteWithChildren
  '/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/users': typeof DashboardUsersRouteRouteWithChildren
  '/profile': typeof DashboardProfileRoute
  '/': typeof DashboardIndexRoute
  '/roles/$name': typeof DashboardRolesNameRouteRouteWithChildren
  '/settings/$': typeof DashboardSettingsSplatRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/roles/': typeof DashboardRolesIndexRoute
  '/users/': typeof DashboardUsersIndexRoute
  '/users/$userId': typeof DashboardUsersUserIdIndexRoute
  '/roles/$name/': typeof DashboardRolesNameDisplayIndexRoute
  '/roles/$name/members': typeof DashboardRolesNameMembersIndexRoute
  '/roles/$name/permissions': typeof DashboardRolesNamePermissionsIndexRoute
}
export interface FileRoutesByTo {
  '/accept-invitation': typeof AcceptInvitationRoute
  '/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/profile': typeof DashboardProfileRoute
  '/': typeof DashboardIndexRoute
  '/settings/$': typeof DashboardSettingsSplatRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/roles': typeof DashboardRolesIndexRoute
  '/users': typeof DashboardUsersIndexRoute
  '/users/$userId': typeof DashboardUsersUserIdIndexRoute
  '/roles/$name': typeof DashboardRolesNameDisplayIndexRoute
  '/roles/$name/members': typeof DashboardRolesNameMembersIndexRoute
  '/roles/$name/permissions': typeof DashboardRolesNamePermissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/_dashboard/roles': typeof DashboardRolesRouteRouteWithChildren
  '/_dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/_dashboard/users': typeof DashboardUsersRouteRouteWithChildren
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/roles/$name': typeof DashboardRolesNameRouteRouteWithChildren
  '/_dashboard/settings/$': typeof DashboardSettingsSplatRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/register/': typeof AuthRegisterIndexRoute
  '/_dashboard/roles/': typeof DashboardRolesIndexRoute
  '/_dashboard/users/': typeof DashboardUsersIndexRoute
  '/_dashboard/users/$userId/': typeof DashboardUsersUserIdIndexRoute
  '/_dashboard/roles/$name/_display/': typeof DashboardRolesNameDisplayIndexRoute
  '/_dashboard/roles/$name/members/': typeof DashboardRolesNameMembersIndexRoute
  '/_dashboard/roles/$name/permissions/': typeof DashboardRolesNamePermissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/accept-invitation'
    | '/roles'
    | '/settings'
    | '/users'
    | '/profile'
    | '/'
    | '/roles/$name'
    | '/settings/$'
    | '/login'
    | '/register'
    | '/roles/'
    | '/users/'
    | '/users/$userId'
    | '/roles/$name/'
    | '/roles/$name/members'
    | '/roles/$name/permissions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invitation'
    | '/settings'
    | '/profile'
    | '/'
    | '/settings/$'
    | '/login'
    | '/register'
    | '/roles'
    | '/users'
    | '/users/$userId'
    | '/roles/$name'
    | '/roles/$name/members'
    | '/roles/$name/permissions'
  id:
    | '__root__'
    | '/_auth'
    | '/_dashboard'
    | '/accept-invitation'
    | '/_dashboard/roles'
    | '/_dashboard/settings'
    | '/_dashboard/users'
    | '/_dashboard/profile'
    | '/_dashboard/'
    | '/_dashboard/roles/$name'
    | '/_dashboard/settings/$'
    | '/_auth/login/'
    | '/_auth/register/'
    | '/_dashboard/roles/'
    | '/_dashboard/users/'
    | '/_dashboard/users/$userId/'
    | '/_dashboard/roles/$name/_display/'
    | '/_dashboard/roles/$name/members/'
    | '/_dashboard/roles/$name/permissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/users': {
      id: '/_dashboard/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashboardUsersRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/roles': {
      id: '/_dashboard/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof DashboardRolesRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/users/': {
      id: '/_dashboard/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardUsersRouteRoute
    }
    '/_dashboard/roles/': {
      id: '/_dashboard/roles/'
      path: '/'
      fullPath: '/roles/'
      preLoaderRoute: typeof DashboardRolesIndexRouteImport
      parentRoute: typeof DashboardRolesRouteRoute
    }
    '/_auth/register/': {
      id: '/_auth/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_dashboard/settings/$': {
      id: '/_dashboard/settings/$'
      path: '/$'
      fullPath: '/settings/$'
      preLoaderRoute: typeof DashboardSettingsSplatRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/_dashboard/roles/$name': {
      id: '/_dashboard/roles/$name'
      path: '/$name'
      fullPath: '/roles/$name'
      preLoaderRoute: typeof DashboardRolesNameRouteRouteImport
      parentRoute: typeof DashboardRolesRouteRoute
    }
    '/_dashboard/users/$userId/': {
      id: '/_dashboard/users/$userId/'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof DashboardUsersUserIdIndexRouteImport
      parentRoute: typeof DashboardUsersRouteRoute
    }
    '/_dashboard/roles/$name/permissions/': {
      id: '/_dashboard/roles/$name/permissions/'
      path: '/permissions'
      fullPath: '/roles/$name/permissions'
      preLoaderRoute: typeof DashboardRolesNamePermissionsIndexRouteImport
      parentRoute: typeof DashboardRolesNameRouteRoute
    }
    '/_dashboard/roles/$name/members/': {
      id: '/_dashboard/roles/$name/members/'
      path: '/members'
      fullPath: '/roles/$name/members'
      preLoaderRoute: typeof DashboardRolesNameMembersIndexRouteImport
      parentRoute: typeof DashboardRolesNameRouteRoute
    }
    '/_dashboard/roles/$name/_display/': {
      id: '/_dashboard/roles/$name/_display/'
      path: '/'
      fullPath: '/roles/$name/'
      preLoaderRoute: typeof DashboardRolesNameDisplayIndexRouteImport
      parentRoute: typeof DashboardRolesNameRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardRolesNameRouteRouteChildren {
  DashboardRolesNameDisplayIndexRoute: typeof DashboardRolesNameDisplayIndexRoute
  DashboardRolesNameMembersIndexRoute: typeof DashboardRolesNameMembersIndexRoute
  DashboardRolesNamePermissionsIndexRoute: typeof DashboardRolesNamePermissionsIndexRoute
}

const DashboardRolesNameRouteRouteChildren: DashboardRolesNameRouteRouteChildren =
  {
    DashboardRolesNameDisplayIndexRoute: DashboardRolesNameDisplayIndexRoute,
    DashboardRolesNameMembersIndexRoute: DashboardRolesNameMembersIndexRoute,
    DashboardRolesNamePermissionsIndexRoute:
      DashboardRolesNamePermissionsIndexRoute,
  }

const DashboardRolesNameRouteRouteWithChildren =
  DashboardRolesNameRouteRoute._addFileChildren(
    DashboardRolesNameRouteRouteChildren,
  )

interface DashboardRolesRouteRouteChildren {
  DashboardRolesNameRouteRoute: typeof DashboardRolesNameRouteRouteWithChildren
  DashboardRolesIndexRoute: typeof DashboardRolesIndexRoute
}

const DashboardRolesRouteRouteChildren: DashboardRolesRouteRouteChildren = {
  DashboardRolesNameRouteRoute: DashboardRolesNameRouteRouteWithChildren,
  DashboardRolesIndexRoute: DashboardRolesIndexRoute,
}

const DashboardRolesRouteRouteWithChildren =
  DashboardRolesRouteRoute._addFileChildren(DashboardRolesRouteRouteChildren)

interface DashboardSettingsRouteRouteChildren {
  DashboardSettingsSplatRoute: typeof DashboardSettingsSplatRoute
}

const DashboardSettingsRouteRouteChildren: DashboardSettingsRouteRouteChildren =
  {
    DashboardSettingsSplatRoute: DashboardSettingsSplatRoute,
  }

const DashboardSettingsRouteRouteWithChildren =
  DashboardSettingsRouteRoute._addFileChildren(
    DashboardSettingsRouteRouteChildren,
  )

interface DashboardUsersRouteRouteChildren {
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
  DashboardUsersUserIdIndexRoute: typeof DashboardUsersUserIdIndexRoute
}

const DashboardUsersRouteRouteChildren: DashboardUsersRouteRouteChildren = {
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
  DashboardUsersUserIdIndexRoute: DashboardUsersUserIdIndexRoute,
}

const DashboardUsersRouteRouteWithChildren =
  DashboardUsersRouteRoute._addFileChildren(DashboardUsersRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardRolesRouteRoute: typeof DashboardRolesRouteRouteWithChildren
  DashboardSettingsRouteRoute: typeof DashboardSettingsRouteRouteWithChildren
  DashboardUsersRouteRoute: typeof DashboardUsersRouteRouteWithChildren
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardRolesRouteRoute: DashboardRolesRouteRouteWithChildren,
  DashboardSettingsRouteRoute: DashboardSettingsRouteRouteWithChildren,
  DashboardUsersRouteRoute: DashboardUsersRouteRouteWithChildren,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
