/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardUsersRouteRouteImport } from './routes/_dashboard/users/route'
import { Route as DashboardSettingsRouteRouteImport } from './routes/_dashboard/settings/route'
import { Route as DashboardLogsRouteRouteImport } from './routes/_dashboard/logs/route'
import { Route as DashboardUsersIndexRouteImport } from './routes/_dashboard/users/index'
import { Route as DashboardAccountIndexRouteImport } from './routes/_dashboard/account/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/_auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as DashboardSettingsSplatRouteImport } from './routes/_dashboard/settings/$'
import { Route as DashboardUsersUserIdIndexRouteImport } from './routes/_dashboard/users/$userId/index'

const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersRouteRoute = DashboardUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRouteRoute = DashboardSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLogsRouteRoute = DashboardLogsRouteRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardUsersRouteRoute,
} as any)
const DashboardAccountIndexRoute = DashboardAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardSettingsSplatRoute = DashboardSettingsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DashboardSettingsRouteRoute,
} as any)
const DashboardUsersUserIdIndexRoute =
  DashboardUsersUserIdIndexRouteImport.update({
    id: '/$userId/',
    path: '/$userId/',
    getParentRoute: () => DashboardUsersRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/accept-invitation': typeof AcceptInvitationRoute
  '/logs': typeof DashboardLogsRouteRoute
  '/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/users': typeof DashboardUsersRouteRouteWithChildren
  '/': typeof DashboardIndexRoute
  '/settings/$': typeof DashboardSettingsSplatRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/account': typeof DashboardAccountIndexRoute
  '/users/': typeof DashboardUsersIndexRoute
  '/users/$userId': typeof DashboardUsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/accept-invitation': typeof AcceptInvitationRoute
  '/logs': typeof DashboardLogsRouteRoute
  '/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/': typeof DashboardIndexRoute
  '/settings/$': typeof DashboardSettingsSplatRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/account': typeof DashboardAccountIndexRoute
  '/users': typeof DashboardUsersIndexRoute
  '/users/$userId': typeof DashboardUsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/_dashboard/logs': typeof DashboardLogsRouteRoute
  '/_dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/_dashboard/users': typeof DashboardUsersRouteRouteWithChildren
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/settings/$': typeof DashboardSettingsSplatRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/register/': typeof AuthRegisterIndexRoute
  '/_dashboard/account/': typeof DashboardAccountIndexRoute
  '/_dashboard/users/': typeof DashboardUsersIndexRoute
  '/_dashboard/users/$userId/': typeof DashboardUsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/accept-invitation'
    | '/logs'
    | '/settings'
    | '/users'
    | '/'
    | '/settings/$'
    | '/login'
    | '/register'
    | '/account'
    | '/users/'
    | '/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invitation'
    | '/logs'
    | '/settings'
    | '/'
    | '/settings/$'
    | '/login'
    | '/register'
    | '/account'
    | '/users'
    | '/users/$userId'
  id:
    | '__root__'
    | '/_auth'
    | '/_dashboard'
    | '/accept-invitation'
    | '/_dashboard/logs'
    | '/_dashboard/settings'
    | '/_dashboard/users'
    | '/_dashboard/'
    | '/_dashboard/settings/$'
    | '/_auth/login/'
    | '/_auth/register/'
    | '/_dashboard/account/'
    | '/_dashboard/users/'
    | '/_dashboard/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/users': {
      id: '/_dashboard/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashboardUsersRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/logs': {
      id: '/_dashboard/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof DashboardLogsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/users/': {
      id: '/_dashboard/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardUsersRouteRoute
    }
    '/_dashboard/account/': {
      id: '/_dashboard/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof DashboardAccountIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/register/': {
      id: '/_auth/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_dashboard/settings/$': {
      id: '/_dashboard/settings/$'
      path: '/$'
      fullPath: '/settings/$'
      preLoaderRoute: typeof DashboardSettingsSplatRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/_dashboard/users/$userId/': {
      id: '/_dashboard/users/$userId/'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof DashboardUsersUserIdIndexRouteImport
      parentRoute: typeof DashboardUsersRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardSettingsRouteRouteChildren {
  DashboardSettingsSplatRoute: typeof DashboardSettingsSplatRoute
}

const DashboardSettingsRouteRouteChildren: DashboardSettingsRouteRouteChildren =
  {
    DashboardSettingsSplatRoute: DashboardSettingsSplatRoute,
  }

const DashboardSettingsRouteRouteWithChildren =
  DashboardSettingsRouteRoute._addFileChildren(
    DashboardSettingsRouteRouteChildren,
  )

interface DashboardUsersRouteRouteChildren {
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
  DashboardUsersUserIdIndexRoute: typeof DashboardUsersUserIdIndexRoute
}

const DashboardUsersRouteRouteChildren: DashboardUsersRouteRouteChildren = {
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
  DashboardUsersUserIdIndexRoute: DashboardUsersUserIdIndexRoute,
}

const DashboardUsersRouteRouteWithChildren =
  DashboardUsersRouteRoute._addFileChildren(DashboardUsersRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardLogsRouteRoute: typeof DashboardLogsRouteRoute
  DashboardSettingsRouteRoute: typeof DashboardSettingsRouteRouteWithChildren
  DashboardUsersRouteRoute: typeof DashboardUsersRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAccountIndexRoute: typeof DashboardAccountIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardLogsRouteRoute: DashboardLogsRouteRoute,
  DashboardSettingsRouteRoute: DashboardSettingsRouteRouteWithChildren,
  DashboardUsersRouteRoute: DashboardUsersRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAccountIndexRoute: DashboardAccountIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
