
// 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑
// 🛑 THIS IS AN AUTOGENERATED FILE - DO NOT EDIT DIRECTLY 🛑
// 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑

/* eslint-disable */
export type CoercedEnvSchema = {
  /**
   * **APP_ENV**
   * Application
   */
  APP_ENV: "development" | "production";

  /**
   * **APP_URL**
   * Frontend origin
   */
  APP_URL: string;

  /**
   * **APP_HOST**
   */
  APP_HOST: string;

  /**
   * **APP_PORT**
   */
  APP_PORT: number;

  /**
   * **API_URL**
   */
  API_URL: string;

  /**
   * **DATABASE_URL** 🔐 _sensitive_
   * Database
   */
  DATABASE_URL: string;

  /**
   * **JWT_SECRET** 🔐 _sensitive_
   * Security — generate with: openssl rand -base64 32
   */
  JWT_SECRET: string;

};


declare module 'varlock/env' {
  export interface TypedEnvSchema extends Readonly<CoercedEnvSchema> {}
  export interface PublicTypedEnvSchema extends Readonly<Pick<CoercedEnvSchema, 'APP_ENV' | 'APP_URL' | 'APP_HOST' | 'APP_PORT' | 'API_URL'>> {}
}


export type EnvSchemaAsStrings = {
  [Property in keyof CoercedEnvSchema]:
    CoercedEnvSchema[Property] extends string ? CoercedEnvSchema[Property]
      : (CoercedEnvSchema[Property] extends boolean ? ('true' | 'false') : string)
};

declare global {

  // add types for global process.env
  namespace NodeJS {
    interface ProcessEnv extends EnvSchemaAsStrings {}
  }
}
